import './globals.css'
import {Inter} from 'next/font/google'
import {Provider} from "react-redux";
import store from "@/core/redux/store";
import {persistStore} from "redux-persist";
import {PersistGate} from "redux-persist/integration/react";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  let persistor = persistStore(store)

  return (
    <html lang="en">
      <Provider store={store}>
        <PersistGate persistor={persistor}>
          <body className={inter.className}>{children}</body>
        </PersistGate>
      </Provider>
    </html>
  )
}
